apiVersion: apps/v1
kind: Deployment
metadata:
  name: presentation-tier-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presentation-layer
  template:
    metadata:
      labels:
        app: presentation-layer
    spec:
      containers:
        - name: presentation-layer
          image: 510567620487.dkr.ecr.ap-south-1.amazonaws.com/presentation-tier:latest
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: presentation-layer-service
spec:
  type: NodePort
  selector:
    app: presentation-layer
  ports:
    - nodePort: 31480
      port: 4200
      targetPort: 80

